### ISSUE TITLE
Can this be used with the A-Frame CDN?

### ISSUE THREAD

**Issue by gmlewis** [murongg/vue3-lazyload#1]
I would like to allow one of my Vue3 pages to pull in the A-Frame CDN on-demand but not have to load it into the full Vue3 SPA.

I tried this:

```html
<template>
  <script v-lazy="{ src: 'https://aframe.io/releases/1.1.0/aframe.min.js' }" />
  <a-scene>
     ...
  </a-scene>
</template>
```

but Vue3 complains with this error message:

```
VueCompilerError: Tags with side effect (<script> and <style>) are ignored in client component templates.
```

Do you have any ideas on how this could be used to pull the A-Frame CDN into the Vue3 app lazily?

**Comment by murongg** [comment]
You want use lazyload plugin load  A-Frame CDN resources?

**Comment by gmlewis** [comment]
> You want use lazyload plugin load A-Frame CDN resources?

Yes, but maybe there is a better way that I'm missing?

**Comment by murongg** [comment]
My plug-in cannot achieve this function,It is only for vue3 <img /> tag!
