### ISSUE TITLE
Lazyloading doesn't work in Capacitor android app.

### ISSUE THREAD

**Issue by mashrurbd** [murongg/vue3-lazyload#21]
Please let me know why Lazyloading doesn't work in Capacitor android app? 

The plugin works great when I use it in web app. But when I compile it to an Android app using Capacitor, the lazyload doesn't work.

**Comment by murongg** [comment]
Doesn't the Android browser work?

**Comment by mashrurbd** [comment]
> Doesn't the Android browser work?

Unfortunately it doesn't work when I build the Android app. But it works perfectly when I test it using development server.

**Comment by murongg** [comment]
@mashrurbd 
lazyload depend on IntersectionObserver，see: https://developer.mozilla.org/zh-CN/docs/Web/API/IntersectionObserver,
view a list of compatible browsers

**Comment by mashrurbd** [comment]
Solved it. It seems the assets I am referring to as error image and loading image gets renamed after build. 

So I had to copy them after build to www/assets and everything seems working. 😇
