### ISSUE TITLE
If some devices are not supported IntersectionObserver ,it will prompt to Error:Not support IntersectionObserver!

### ISSUE THREAD

**Issue by Luffyying** [murongg/vue3-lazyload#22]

**Comment by murongg** [comment]
lazyload depends on IntersectionObserver，see: https://developer.mozilla.org/zh-CN/docs/Web/API/IntersectionObserver

**Comment by Luffyying** [comment]
> 

thanks, Is it compatible, like import 'intersection-observer' ?
