### ISSUE TITLE
 TypeError: Failed to execute 'unobserve' on 'IntersectionObserver': parameter 1 is not of type 'Element'.

### ISSUE THREAD

**Issue by binvb** [murongg/vue3-lazyload#30]
i was get error from user report, but i can not find why this happend, can you help?

**Comment by murongg** [comment]
Can you provide mini repo?

**Comment by binvb** [comment]
> Can you provide mini repo?

i found the @latest version already fix: 
```
  public update(el: HTMLElement, binding: string | DirectiveBinding<string | ValueFormatterObject>): void {
    if (!el)
      return
    this._realObserver(el)?.unobserve(el)
    const { src, error, lifecycle, delay } = this._valueFormatter(typeof binding === 'string' ? binding : binding.value)
    this._initIntersectionObserver(el, src, error, lifecycle, delay)
  }
```

but i was wondering when the el object will return null, it's glad to get your answer.

**Comment by murongg** [comment]
> > Can you provide mini repo?
> 
> i found the @latest version already fix this:
> 
> ```
>   public update(el: HTMLElement, binding: string | DirectiveBinding<string | ValueFormatterObject>): void {
>     if (!el)
>       return
>     this._realObserver(el)?.unobserve(el)
>     const { src, error, lifecycle, delay } = this._valueFormatter(typeof binding === 'string' ? binding : binding.value)
>     this._initIntersectionObserver(el, src, error, lifecycle, delay)
>   }
> ```
> 
> but i was wondering when the el object will return null, it's glad to get your answer.

When the dom has not been mounted or unmounted dom
