### ISSUE TITLE
Breakage between 0.2.5-beta and 0.3.0 for older mobile browsers

### ISSUE THREAD

**Issue by david-english-sweetwater** [murongg/vue3-lazyload#36]
Version `0.3.0` and higher don't seem to work on iPhone 11 iOS version 13.0, for either Chrome or Safari.

The Vue components seem to never load.

This was discovered while doing compatibility testing (we're using BrowserStack). iPhone 11 iOS version 15.0 for both Chrome and Safari seem to be unaffected, and work as expected. We've had to downgrade to `0.2.5-beta` to get our site working with the older iOS version. 

Chome version on iPhone 11 with iOS 13.0 (nothing in the console output, unfortunately):
<img width="482" alt="Screen Shot 2022-12-07 at 11 31 23 AM" src="https://user-images.githubusercontent.com/120043086/206238400-b480be2b-5139-4021-8bf4-5a9377eb1151.png">

Safari did have this error in the console, but it's not a lot to go on:

<img width="470" alt="Screen Shot 2022-12-07 at 11 44 31 AM" src="https://user-images.githubusercontent.com/120043086/206239045-e962efc1-476d-488a-9ca6-d067fc9a1c7d.png">

**Comment by david-english-sweetwater** [comment]
I was able to narrow this problem down to the new optional chaining syntax used in the `0.3.0` version (e.g. `this._realObserver(el)?.unobserve(el);`). 

We're using the optional chaining syntax in other areas of our application with no issues. We also have the `@babel/plugin-proposal-optional-chaining` plugin installed, but it doesn't seem to be transpiling the `vue3-lazyload` import.

Any ideas?

**Comment by david-english-sweetwater** [comment]
It looks like the `lib` and `module` targets are set to `esnext` in the [tsconfig.json](https://github.com/murongg/vue3-lazyload/blob/main/tsconfig.json#L5).

Would it be possible to have that target `es2017` or `es2020` so that compatible code is generated?

**Comment by david-english-sweetwater** [comment]
We found an `es5` target that we could import, which meets our needs:
```
import { default as vueLazyLoad } from '../../../node_modules/vue3-lazyload/dist/index.min.js'; 

app.use(vueLazyLoad.install,{
    loading: 'https://server/loader.gif'
});
```

**Comment by murongg** [comment]
What you use Vue version?

**Comment by whmk-m** [comment]
> What are you use Vue version?

Using Vue 3.0, I also encountered the following similar problems：

You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     if (!el)
|       return;
>     this._realObserver(el)?.unobserve(el);
|     const { src, error, lifecycle, delay } = this._valueFormatter(typeof binding === "string" ? binding : binding.value);
|     this._initIntersectionObserver(el, src, error, lifecycle, delay);

**Comment by david-english-sweetwater** [comment]
We're using Vue 3.0 as well.
