### ISSUE TITLE
Not working with path alias

### ISSUE THREAD

**Issue by ngekoding** [murongg/vue3-lazyload#38]
Just trying with NuxtJS and applying the src with path alias, then get 404 not found.

```vue
<img v-lazy="{ src: '@/assets/img/image.png' }">
```

It must be resolved as default behavior, it is like become `http://localhost:3000/_nuxt/assets/img/image.png`, but when using the v-lazy it still with the typed src as `@/assets/img/image.png`.

How to solve this? Thanks in advance

**Comment by murongg** [comment]
try it: 
```
# template
<img v-lazy="{ src: imageResource}">

# script 
import imageResource from "@/assets/img/image.png"
```
