### ISSUE TITLE
loaded attribute not updated for all elements

### ISSUE THREAD

**Issue by shanmuga3** [murongg/vue3-lazyload#4]
lazy="loaded" not updated for all images. it updates only last element.

![lazy](https://user-images.githubusercontent.com/38732797/120063436-d2d01380-c084-11eb-88d6-a1a49bee57a0.png)

**Comment by murongg** [comment]
ok, I will continue to maintain this project

**Comment by dennisbaum** [comment]
same for me. only one out of three images gets an updated state, but it was loaded... it would also be very cute, if images with display: none wouldn't be loaded, until display changes. tnx!
