### ISSUE TITLE
Problem with heic format

### ISSUE THREAD

**Issue by vaske** [murongg/vue3-lazyload#41]
I was trying to allow usage of heic format and notice that using lazy loading it have problem with it

```
index.mjs:144 Uncaught Error: Image failed to load!And failed src was: data:image/heic;base64,....
```

Do you plan to add support for it anytime or?

**Comment by murongg** [comment]
Is you use base64 load heic resource?

**Comment by murongg** [comment]
I discovered through a Google search that HEIC is not a commonly used image format. To access it, a decoder is required, which means that browsers do not inherently support this format.
